# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drama',
            name='entertainment',
        ),
        migrations.DeleteModel(
            name='Drama',
        ),
        migrations.RemoveField(
            model_name='entertainment',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='fill_in_blank_answer',
            name='question',
        ),
        migrations.DeleteModel(
            name='Fill_In_Blank_Answer',
        ),
        migrations.RemoveField(
            model_name='fill_in_blank_question',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Fill_In_Blank_Question',
        ),
        migrations.RemoveField(
            model_name='long_translate_answer',
            name='question',
        ),
        migrations.DeleteModel(
            name='Long_Translate_Answer',
        ),
        migrations.RemoveField(
            model_name='long_translate_question',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Long_Translate_Question',
        ),
        migrations.RemoveField(
            model_name='matching_question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='multiple_choice_answer',
            name='question',
        ),
        migrations.DeleteModel(
            name='Multiple_Choice_Answer',
        ),
        migrations.RemoveField(
            model_name='multiple_choice_question',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Multiple_Choice_Question',
        ),
        migrations.RemoveField(
            model_name='pair1',
            name='question',
        ),
        migrations.DeleteModel(
            name='Matching_Question',
        ),
        migrations.RemoveField(
            model_name='pair2',
            name='question',
        ),
        migrations.DeleteModel(
            name='Pair1',
        ),
        migrations.DeleteModel(
            name='Pair2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='short_translate_answer',
            name='question',
        ),
        migrations.DeleteModel(
            name='Short_Translate_Answer',
        ),
        migrations.RemoveField(
            model_name='short_translate_question',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Short_Translate_Question',
        ),
        migrations.RemoveField(
            model_name='song',
            name='entertainment',
        ),
        migrations.DeleteModel(
            name='Entertainment',
        ),
        migrations.RemoveField(
            model_name='song_genre',
            name='song',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.DeleteModel(
            name='Song_Genre',
        ),
        migrations.RemoveField(
            model_name='true_false_question',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='True_False_Question',
        ),
        migrations.RemoveField(
            model_name='video',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.RemoveField(
            model_name='video_answer',
            name='question',
        ),
        migrations.DeleteModel(
            name='Video_Answer',
        ),
        migrations.RemoveField(
            model_name='video_question',
            name='video',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='Video_Question',
        ),
    ]
